### PR TITLE
Correct folder structure for SimpleCov reporting

### PR DESCRIPTION
**Pull request by richrace**
## What

Update config for SimpleCov. Use Rails presets + add folders.

## Checklist

Before you ask people to review this PR:

- [ ] Tests and linters should be passing
- [ ] Github should not be reporting conflicts; you should have recently run `git rebase master`.
- [ ] Avoid mixing whitespace changes with code changes in the same commit. These make diffs harder to read and conflicts more likely.
- [ ] You should have looked at the diff against master and ensured that nothing unexpected is included in your changes.
- [ ] You should have checked that the commit messages say why the change was made.

### CODE REVIEW

**Comment by richrace** [comment]
Yup these two files are now being included and tested. 

Are we using them? If not, can we remove them?


Screenshot 2020-04-29 at 09 21 42

**Comment by mpw5** [comment]
I'm pretty sure we're not using them, but I'm not sure what the implication of removing them would be (does Rails do anything with ActionCable under the hood?). I guess deleting the files and running the tests will tell us!

Or we could just exclude them from code coverage - `add_filter 'app/channels'` in the `SimpleCov.start` block.

**Comment by archferns** [comment]
We can delete those, as this is mainly an API only app.

**Comment by richrace** [comment]
Cool. I'll make a separate PR for those changes then rebase this branch.

**Pull request merged**
